# Generated by Django 3.2.18 on 2023-05-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sagas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('saga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arcs', to='sagas.saga')),
            ],
        ),
    ]
