# Generated by Django 3.2.18 on 2023-05-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mangas', '0001_initial'),
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('alias', models.TextField(blank=True, null=True)),
                ('species', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.CharField(blank=True, max_length=50, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('contracted_devils', models.TextField(blank=True, null=True)),
                ('contracted_humans', models.TextField(blank=True, null=True)),
                ('is_main', models.BooleanField(blank=True, null=True)),
                ('anime_debut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='animes.anime')),
                ('manga_debut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='mangas.manga')),
            ],
        ),
    ]
