# Generated by Django 3.2.18 on 2023-05-23 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcs', '0001_initial'),
        ('volumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='saga',
        ),
        migrations.AddField(
            model_name='volume',
            name='arc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumes', to='arcs.arc'),
        ),
    ]
