# Generated by Django 3.2.18 on 2023-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0003_remove_volume_arc'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
